apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chat-history-service.fullname" . }}
  labels:
    app: {{ include "chat-history-service.name" . }}
    {{- include "chat-history-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "chat-history-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "chat-history-service.name" . }}
        {{- include "chat-history-service.labels" . | nindent 8 }}
    spec:
      serviceAccountName: chat-history-service-sa
      containers:
      - name: {{ include "chat-history-service.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
        - name: DATABASE_PATH
          value: {{ .Values.env.databasePath }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
